# Data Preprocessing

In [1]:
# import packages
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import csv

# Adjust notebook settings to widen the notebook
from IPython.core.display import display, HTML
display(HTML("<style>.container {width:85% !important;}</style>"))
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

In [2]:
# ## downloaded 2015-2019 datasets from NSDUH
# nsduh2019 = pd.read_csv("./Data/nsduh2019.csv")
# nsduh2018 = pd.read_csv("./Data/nsduh2018.csv")
# nsduh2017 = pd.read_csv("./Data/nsduh2017.csv")
# nsduh2016 = pd.read_csv("./Data/nsduh2016.csv")
# nsduh2015 = pd.read_csv("./Data/nsduh2015.csv")

# ## join datasets from 2015-2019 on common columns
# nsduh = pd.concat([nsduh2015, nsduh2016], axis=0, join="inner")
# nsduh = pd.concat([nsduh, nsduh2017], axis=0, join="inner")
# nsduh = pd.concat([nsduh, nsduh2018], axis=0, join="inner")
# nsduh2019.columns = nsduh2019.columns.str.upper()
# nsduh = pd.concat([nsduh, nsduh2019], axis=0, join="inner")

# ## save merged dataset
# nsduh.to_csv("./Data/nsduh_original.csv")

# df_chunk = pd.read_csv('./Data/nsduh_original.csv',chunksize=1000000)
# df_original = pd.concat(df_chunk)

In [3]:
# # chunk15.head(2) # 2015 : File date = 02/15/2018
# # chunk16.head(2) # 2016 : File date = 02/28/2018
# # chunk17.head(2) # 2017 : File date = 10/09/2018
# # chunk18.head(2) # 2018 : File date = 10/08/2019
# # chunk19.head(2) # 2019 : File date = 10/09/2020

# df_original['FILEDATE'] = df_original['FILEDATE'].replace(['02/15/2018','02/28/2018','10/09/2018','10/08/2019','10/09/2020'],[2015, 2016, 2017, 2018, 2019])

In [4]:
# df_reduced = df_original[['QUESTID2', 'FILEDATE', 'AMHINP2', 'AMHOUTP3', 'AMHRX2', 'AMHTXRC3', 'AMHSVTYP', 'AMHTXND2', 'AMHTXAND', 'MHLMNT3', 'MHLTHER3', 'MHLDOC3', 'MHLCLNC3', 'MHLDTMT3', 'MHLSCHL3', 'MHLOTH3', 'MHPDSLF2', 'MHPDOFM2', 'MHPDPHI2', 'MHPDMCR2', 'MHPDMCD2', 'MHPDREH2', 'MHPDEMP2', 'MHPDMIL2', 'MHPDPUB2', 'MHPDPRV2', 'MHPDFRE2', 'MHRCOST2', 'MHRNBRS2', 'MHRJOBS2', 'MHRNCOV2', 'MHRENUF2', 'MHRWHER2', 'MHRCFID2', 'MHRCMIT2', 'MHRNOND2', 'MHRHAND2', 'MHRNOHP2', 'MHRTIME2', 'MHRFOUT2', 'MHRTRAN2', 'MHRSOTH2', 'RCVMHOSPTX', 'RCVMHNSPTX', 'RCVSPTXNMH', 'RCVMHASPTX', 'DSTWORST', 'DSTNRV12', 'DSTHOP12', 'DSTRST12', 'DSTCHR12', 'DSTEFF12', 'DSTNGD12', 'IMPREMEM', 'IMPCONCN', 'IMPGOUT', 'IMPGOUTM', 'IMPPEOP', 'IMPPEOPM', 'IMPSOC', 'IMPSOCM', 'IMPHHLD', 'IMPHHLDM', 'IMPRESP', 'IMPRESPM', 'IMPWORK', 'IMPWEEKS', 'IMPDYFRQ', 'IMPYDAYS', 'SUICTHNK', 'SUICPLAN', 'SUICTRY', 'K6SCMON', 'SPDMON', 'K6SCYR', 'K6SCMAX', 'SPDYR', 'MHSUITHK','MHSUIPLN', 'MHSUITRY', 'SMMIYR_U', 'MMIYR_U', 'LMIYR_U', 'LMMIYRU', 'MI_CAT_U', 'SMISUDPY', 'AMISUDPY', 'LMMISUDPY', 'AMDELT', 'AMDEYR','ATXMDEYR', 'ARXMDEYR', 'AMDETXRX','IRSEX', 'IREDUHIGHST2','CATAGE', 'CATAG2', 'CATAG3', 'CATAG6', 'SEXAGE', 'NEWRACE2', 'SEXRACE', 'EDUHIGHCAT', 'HEALTH2', 'WRKSKIPMO', 'WRKSICKMO', 'WRKSTATWK2', 'WRKDPSTWK', 'WRKHADJOB', 'WRKDHRSWK2', 'WRK35WKUS', 'WRKRSNNOT', 'WRKRSNJOB', 'WRKEFFORT', 'WRKDPSTYR', 'WRKSELFEM', 'WRKNUMJOB2', 'WRKNJBPYR', 'WRKNJBWKS', 'WRKLASTYR2', 'WRKSICKMO', 'WRKSKIPMO','WRKDRGHLP','IRWRKSTAT18','IRMEDICR','IRMCDCHP','IRCHMPUS','IRPRVHLT','IROTHHLT','ANYHLTI2', 'IRINSUR4','IRFAMSOC','IRFAMSSI','IRFSTAMP','IRFAMPMT','IRFAMSVC','IRWELMOS','IRPINC3','IRFAMIN3','GOVTPROG','INCOME','POVERTY3','PDEN10','COUTYP4']]
# df_reduced.to_csv('./Data/nsduh_reduced_data.csv')

In [6]:
df_chunk = pd.read_csv('./Data/nsduh_reduced_data.csv',chunksize=1000000) # reduced dataset saved in google drive
df = pd.concat(df_chunk)

In [7]:
# Get all column names in df
print(list(df.columns))

['Unnamed: 0', 'QUESTID2', 'FILEDATE', 'AMHINP2', 'AMHOUTP3', 'AMHRX2', 'AMHTXRC3', 'AMHSVTYP', 'AMHTXND2', 'AMHTXAND', 'MHLMNT3', 'MHLTHER3', 'MHLDOC3', 'MHLCLNC3', 'MHLDTMT3', 'MHLSCHL3', 'MHLOTH3', 'MHPDSLF2', 'MHPDOFM2', 'MHPDPHI2', 'MHPDMCR2', 'MHPDMCD2', 'MHPDREH2', 'MHPDEMP2', 'MHPDMIL2', 'MHPDPUB2', 'MHPDPRV2', 'MHPDFRE2', 'MHRCOST2', 'MHRNBRS2', 'MHRJOBS2', 'MHRNCOV2', 'MHRENUF2', 'MHRWHER2', 'MHRCFID2', 'MHRCMIT2', 'MHRNOND2', 'MHRHAND2', 'MHRNOHP2', 'MHRTIME2', 'MHRFOUT2', 'MHRTRAN2', 'MHRSOTH2', 'RCVMHOSPTX', 'RCVMHNSPTX', 'RCVSPTXNMH', 'RCVMHASPTX', 'DSTWORST', 'DSTNRV12', 'DSTHOP12', 'DSTRST12', 'DSTCHR12', 'DSTEFF12', 'DSTNGD12', 'IMPREMEM', 'IMPCONCN', 'IMPGOUT', 'IMPGOUTM', 'IMPPEOP', 'IMPPEOPM', 'IMPSOC', 'IMPSOCM', 'IMPHHLD', 'IMPHHLDM', 'IMPRESP', 'IMPRESPM', 'IMPWORK', 'IMPWEEKS', 'IMPDYFRQ', 'IMPYDAYS', 'SUICTHNK', 'SUICPLAN', 'SUICTRY', 'K6SCMON', 'SPDMON', 'K6SCYR', 'K6SCMAX', 'SPDYR', 'MHSUITHK', 'MHSUIPLN', 'MHSUITRY', 'SMMIYR_U', 'MMIYR_U', 'LMIYR_U', 'LMMIYR

In [8]:
df_trimmed = df[['QUESTID2', 'FILEDATE', 'AMHINP2', 'AMHOUTP3', 'AMHRX2', 'AMHTXRC3', 'AMHSVTYP', 'AMHTXND2', 'AMHTXAND', 'MHLMNT3', 'MHLTHER3', 'MHLDOC3', 'MHLCLNC3', 'MHLDTMT3', 'MHLSCHL3', 'MHLOTH3', 'MHPDSLF2', 'MHPDOFM2', 'MHPDPHI2', 'MHPDMCR2', 'MHPDMCD2', 'MHPDREH2', 'MHPDEMP2', 'MHPDMIL2', 'MHPDPUB2', 'MHPDPRV2', 'MHPDFRE2', 'MHRCOST2', 'MHRNBRS2', 'MHRJOBS2', 'MHRNCOV2', 'MHRENUF2', 'MHRWHER2', 'MHRCFID2', 'MHRCMIT2', 'MHRNOND2', 'MHRHAND2', 'MHRNOHP2', 'MHRTIME2', 'MHRFOUT2', 'MHRTRAN2', 'MHRSOTH2', 'RCVMHOSPTX', 'RCVMHNSPTX', 'RCVSPTXNMH', 'RCVMHASPTX', 'DSTWORST', 'DSTNRV12', 'DSTHOP12', 'DSTRST12', 'DSTCHR12', 'DSTEFF12', 'DSTNGD12', 'IMPREMEM', 'IMPCONCN', 'IMPGOUT', 'IMPGOUTM', 'IMPPEOP', 'IMPPEOPM', 'IMPSOC', 'IMPSOCM', 'IMPHHLD', 'IMPHHLDM', 'IMPRESP', 'IMPRESPM', 'IMPWORK', 'IMPWEEKS', 'IMPDYFRQ', 'IMPYDAYS', 'SUICTHNK', 'SUICPLAN', 'SUICTRY', 'K6SCMON', 'SPDMON', 'K6SCYR', 'K6SCMAX', 'SPDYR', 'MHSUITHK','MHSUIPLN', 'MHSUITRY', 'SMMIYR_U', 'MMIYR_U', 'LMIYR_U', 'LMMIYRU', 'MI_CAT_U', 'SMISUDPY', 'AMISUDPY', 'LMMISUDPY', 'AMDELT', 'AMDEYR','ATXMDEYR', 'ARXMDEYR', 'AMDETXRX','IRSEX', 'IREDUHIGHST2','CATAGE', 'CATAG2', 'CATAG3', 'CATAG6','SEXAGE', 'NEWRACE2', 'SEXRACE', 'EDUHIGHCAT', 'HEALTH2', 'WRKSTATWK2', 'WRKDPSTWK', 'WRKHADJOB', 'WRKDHRSWK2', 'WRK35WKUS', 'WRKRSNNOT', 'WRKRSNJOB', 'WRKEFFORT', 'WRKDPSTYR', 'WRKSELFEM', 'WRKNUMJOB2', 'WRKNJBPYR', 'WRKNJBWKS', 'WRKLASTYR2', 'WRKSICKMO', 'WRKSKIPMO','WRKDRGHLP','IRWRKSTAT18','IRMEDICR','IRMCDCHP','IRCHMPUS','IRPRVHLT','IROTHHLT','ANYHLTI2', 'IRINSUR4','IRFAMSOC','IRFAMSSI','IRFSTAMP','IRFAMPMT','IRFAMSVC','IRWELMOS','IRPINC3','IRFAMIN3','GOVTPROG','INCOME','POVERTY3','PDEN10','COUTYP4']]

In [9]:
# df_trimmed.shape # (282768, 148)

In [10]:
df_trimmed = df_trimmed[['QUESTID2', 'FILEDATE', 'AMHINP2', 'AMHOUTP3', 'AMHRX2', 'AMHTXRC3', 'AMHSVTYP', 'AMHTXND2','MHLMNT3', 'MHLTHER3', 'MHLDOC3', 'MHLCLNC3', 'MHLDTMT3', 'MHLSCHL3', 'MHLOTH3', 'MHPDSLF2', 'MHPDOFM2', 'MHPDPHI2', 'MHPDMCR2', 'MHPDMCD2', 'MHPDREH2', 'MHPDEMP2', 'MHPDMIL2', 'MHPDPUB2', 'MHPDPRV2', 'MHPDFRE2', 'MHRCOST2', 'MHRNBRS2', 'MHRJOBS2', 'MHRNCOV2', 'MHRENUF2', 'MHRWHER2', 'MHRCFID2', 'MHRCMIT2', 'MHRNOND2', 'MHRHAND2', 'MHRNOHP2', 'MHRTIME2', 'MHRFOUT2', 'MHRTRAN2', 'MHRSOTH2', 'IMPWEEKS', 'IMPYDAYS', 'SUICTHNK','SUICPLAN', 'SUICTRY', 'K6SCMON', 'SPDMON', 'K6SCYR', 'K6SCMAX', 'SPDYR', 'MHSUITHK', 'MHSUIPLN', 'MHSUITRY', 'SMMIYR_U', 'MMIYR_U', 'LMIYR_U', 'LMMIYRU', 'MI_CAT_U', 'SMISUDPY', 'AMISUDPY', 'LMMISUDPY', 'AMDELT', 'AMDEYR', 'ATXMDEYR', 'ARXMDEYR', 'AMDETXRX', 'IRSEX', 'IREDUHIGHST2', 'CATAGE', 'CATAG2', 'CATAG3', 'CATAG6', 'SEXAGE', 'NEWRACE2', 'SEXRACE', 'EDUHIGHCAT', 'HEALTH2', 'WRKSTATWK2','WRKSKIPMO', 'WRKDRGHLP', 'IRWRKSTAT18', 'IRMEDICR', 'IRMCDCHP', 'IRCHMPUS', 'IRPRVHLT', 'IROTHHLT', 'ANYHLTI2', 'IRINSUR4', 'IRFAMSOC', 'IRFAMSSI', 'IRFSTAMP', 'IRFAMPMT', 'IRFAMSVC', 'IRWELMOS', 'IRPINC3', 'IRFAMIN3', 'GOVTPROG', 'INCOME', 'POVERTY3', 'PDEN10', 'COUTYP4']]

In [11]:
# Renaming columns
column_mappings = dict()
with open('Data/nsduh_data_dictionary.csv') as csvfile:
    csvreader = csv.reader(csvfile)
    for row in csvreader:
        column_mappings[row[0]] = row[1]
df_trimmed = df_trimmed.rename(columns=column_mappings)

In [12]:
print(list(df_trimmed.columns))

['Id', 'Year', 'Inpatient_Past_Year', 'Outpatient_Past_Year', 'Prescription_Treatment_Past_Year', 'Any_Treatment_Past_Year', 'Treatment_Type_Past_Year', 'Perceived_Unmet_Need', 'Received_Treatment_At_Clinic_Or_Center', 'Received_Treatment_At_Private_Therapist', 'Received_Treatment_At_NonClinic_Doctor', 'Received_Treatment_At_Medical_Clinic', 'Received_Treatment_At_Day_Hospital', 'Received_Treatment_At_School', 'Received_Treatment_Other', 'Self_Paid', 'Non_Household_Member_Paid', 'Private_Health_Insurance_Paid', 'Medicare_Paid', 'Medicaid_Paid', 'Rehab_Paid', 'Employer_Paid', 'Military_Paid', 'Other_Public_Source_Paid', 'Other_Private_Source_Paid', 'Nobody_Paid', 'No_Treatment_Could_Not_Afford', 'No_Treatment_Feared_Neighbors_Opinion', 'No_Treatment_Feared_Effect_On_Job', 'No_Treatment_Insurance_Not_Covered', 'No_Treatment_Insurance_Not_Covered_Enough', 'No_Treatment_Where_To_Go', 'No_Treatment_Confidentiality_Concerns', 'No_Treatment_Fear_Of_Being_Committed', 'No_Treatment_Didnt_Think_

In [13]:
df_cleaned = df_trimmed.fillna(-1)

In [14]:
df_cleaned = df_cleaned.astype(int)

In [15]:
df_age_filtered = df_cleaned.loc[df_cleaned['Age_Category'] > 1]

In [16]:
df_age_filtered[['Inpatient_Past_Year', 'Outpatient_Past_Year', 'Prescription_Treatment_Past_Year', 'Any_Treatment_Past_Year']] = df_age_filtered[['Inpatient_Past_Year', 'Outpatient_Past_Year', 'Prescription_Treatment_Past_Year', 'Any_Treatment_Past_Year']].replace(2,0)

/Users/chiufengyap/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]


In [17]:
df_age_filtered['Perceived_Unmet_Need'] = df_age_filtered['Perceived_Unmet_Need'].replace(2,0)

<ipython-input-17-d7f38b97ca2c>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_age_filtered['Perceived_Unmet_Need'] = df_age_filtered['Perceived_Unmet_Need'].replace(2,0)


In [18]:
df_age_filtered['Treatment_Type_Past_Year'] = df_age_filtered['Treatment_Type_Past_Year'].replace(8,0)

<ipython-input-18-6a8b86ed125f>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_age_filtered['Treatment_Type_Past_Year'] = df_age_filtered['Treatment_Type_Past_Year'].replace(8,0)


In [19]:
df_age_filtered['Num_Weeks_Mental_Health_Difficulties'] = df_age_filtered['Num_Weeks_Mental_Health_Difficulties'].replace(99,0)

<ipython-input-19-8d84b1e51e33>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_age_filtered['Num_Weeks_Mental_Health_Difficulties'] = df_age_filtered['Num_Weeks_Mental_Health_Difficulties'].replace(99,0)


In [20]:
df_age_filtered['Num_Weeks_Mental_Health_Difficulties'] = df_age_filtered['Num_Weeks_Mental_Health_Difficulties'].replace([85,94,97,98],-1)

<ipython-input-20-08bf032e4cdc>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_age_filtered['Num_Weeks_Mental_Health_Difficulties'] = df_age_filtered['Num_Weeks_Mental_Health_Difficulties'].replace([85,94,97,98],-1)


In [21]:
df_age_filtered['Num_Days_Past_Year_Unable_To_Work'] = df_age_filtered['Num_Days_Past_Year_Unable_To_Work'].replace(999,0)

<ipython-input-21-dabbc50deb83>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_age_filtered['Num_Days_Past_Year_Unable_To_Work'] = df_age_filtered['Num_Days_Past_Year_Unable_To_Work'].replace(999,0)


In [22]:
df_age_filtered['Num_Days_Past_Year_Unable_To_Work'].where(df_age_filtered['Num_Days_Past_Year_Unable_To_Work'] <= 365, -1, inplace=True)

/Users/chiufengyap/opt/anaconda3/lib/python3.8/site-packages/pandas/core/generic.py:9286: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._where(


In [23]:
df_final = df_age_filtered.copy()

In [24]:
df_final[['Serious_Suicidal_Thoughts_Past_12_Months','Suicide_Plan_Past_12_Months','Suicide_Attempt_Past_12_Months']] = df_final[['Serious_Suicidal_Thoughts_Past_12_Months','Suicide_Plan_Past_12_Months','Suicide_Attempt_Past_12_Months']].replace(2,0)
df_final[['Serious_Suicidal_Thoughts_Past_12_Months','Suicide_Plan_Past_12_Months','Suicide_Attempt_Past_12_Months']] = df_final[['Serious_Suicidal_Thoughts_Past_12_Months','Suicide_Plan_Past_12_Months','Suicide_Attempt_Past_12_Months']].replace(99,0)
df_final[['Serious_Suicidal_Thoughts_Past_12_Months','Suicide_Plan_Past_12_Months','Suicide_Attempt_Past_12_Months']] = df_final[['Serious_Suicidal_Thoughts_Past_12_Months','Suicide_Plan_Past_12_Months','Suicide_Attempt_Past_12_Months']].replace([85,94,97,98],-1)

In [25]:
# Drop unneeded columns
df_final.drop(['Serious_Suicidal_Thoughts_Past_12_Months', 'Suicide_Plan_Past_12_Months','Suicide_Attempt_Past_12_Months','Psychological_Distress_Level_Past_Month','Adult_Talked_To_Professional_About_Depressive_Feelings_Past_Year','Adult_Used_RX_Meds_For_Depressive_Feelings_Past_Year', 'Education'], axis=1, inplace=True)

In [26]:
df_final['Serious_Mental_Illness_And_Substance_Abuse'].replace(2,0,inplace=True)

In [27]:
df_final['Any_Mental_Illness_And_Substance_Abuse'].replace(2,0,inplace=True)

In [28]:
df_final['Adult_Past_Year_Major_Depressive_Episode'].replace(2,0,inplace=True)
df_final['Adult_Lifetime_Major_Depressive_Episode'].replace(2,0,inplace=True)

In [29]:
df_final.loc[:,'Has_Medicare':'Family_Receives_Welfare_JobPlacement_Childcare'].replace(2,0,inplace=True)

/Users/chiufengyap/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4524: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().replace(


In [30]:
df_final['EAP_Offered'].replace(2,0,inplace=True)

In [31]:
df_final['Participated_In_One_Or_More_Government_Assistance_Programs'].replace(2,0,inplace=True)

In [32]:
df_final['Overall_Health'].replace(94,-1, inplace=True)
df_final['Overall_Health'].replace(97,-1, inplace=True)
df_final.Overall_Health.unique()

array([ 1,  2,  3,  4, -1])

In [33]:
df_final['Work_Situation_Past_Week'].replace(99,0, inplace=True)
df_final['Work_Situation_Past_Week'].replace(98,-1, inplace=True)
df_final.Work_Situation_Past_Week.unique()

array([ 1,  7,  6,  9, -1,  2,  4,  8,  5,  3])

In [34]:
df_final['Num_Days_Skipped_Work_Past_30_Days'].replace(99,0, inplace=True)
df_final['Num_Days_Skipped_Work_Past_30_Days'].replace(85,-1, inplace=True)
df_final['Num_Days_Skipped_Work_Past_30_Days'].replace(94,-1, inplace=True)
df_final['Num_Days_Skipped_Work_Past_30_Days'].replace(97,-1, inplace=True)
df_final['Num_Days_Skipped_Work_Past_30_Days'].replace(98,-1, inplace=True)
df_final.Num_Days_Skipped_Work_Past_30_Days.unique()

array([ 0,  2,  1,  5,  4, -1, 13,  3,  6,  7, 10, 18, 30, 22, 15, 17,  8,
       16,  9, 23, 20, 14, 21, 12, 28, 11, 25, 24, 19, 27, 29, 26])

In [35]:
df_final['EAP_Offered'].replace(99,-1, inplace=True)
df_final['EAP_Offered'].replace(85,-1, inplace=True)
df_final['EAP_Offered'].replace(94,-1, inplace=True)
df_final['EAP_Offered'].replace(97,-1, inplace=True)
df_final['EAP_Offered'].replace(98,-1, inplace=True)
df_final.EAP_Offered.unique()

array([ 0, -1,  1])

In [36]:
df_final['Adult_Employment_Status'].replace(99, 0, inplace=True)
df_final.Adult_Employment_Status.unique()

array([1, 4, 2, 3])

In [37]:
df_final['Has_Other_Health_Insurance'].replace(99, -1, inplace=True)
df_final.Has_Other_Health_Insurance.unique()

array([-1,  0,  1])

In [38]:
df_final['Covered_By_Any_Health_Insurance'].replace(94, -1, inplace=True)
df_final['Covered_By_Any_Health_Insurance'].replace(97, -1, inplace=True)
df_final['Covered_By_Any_Health_Insurance'].replace(98, -1, inplace=True)
df_final.Covered_By_Any_Health_Insurance.unique()

array([ 1,  0, -1])

In [39]:
df_final['Months_On_Welfare'].replace(99, 0, inplace=True)
df_final.Months_On_Welfare.unique()

array([ 1,  0, 12,  6,  2,  3,  7, 10, 11,  9,  4,  5,  8])

In [40]:
df_final.to_csv('./Data/nsduh_data_cleaned.csv')